- 24h:
    id_type: href
    browser_profile: ''
    web_url: https://www.24h.com.vn/
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //h2[@id='article_sapo']
    - //h2[@id='article_sapo']
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 02/06/2019 21:56
    contain: ''
    crawl_url: https://www.24h.com.vn/tin-tuc-o-to-c332.html
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class='updTm updTmD mrT5']
    - //div[@class='updTm updTmD mrT5']
    topic_type: href
    maximum_url: 50
    get_detail_content: true
    content_xpath:
    - //article[@id='article_body']
    - //article[@id='article_body']
    text_xpath:
    - ./p
    - ./p
    image_box_xpath:
    - .//p[@align='center']
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://www.24h.com.vn/o-to
    minimum_topic_length: 4
    tags: []
    only_quality_post: true
    browser_timeout: 60
    prevent_auto_redirect: false
