- Carbuzz:
    id_type: href
    browser_profile: ''
    web_url: https://carbuzz.com
    timezone: US/Eastern
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@data-src
    - .//img/@data-src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //div[@class='cb-post__body']/p
    - //div[@class='cb-post__body']/p
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 08/12/2020 03:30
    contain: ''
    crawl_url: https://carbuzz.com
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //cb-datetime[@class='cb-post__publish-time']/@datetime
    - //cb-datetime[@class='cb-post__publish-time']/@datetime
    topic_type: href
    maximum_url: 50
    get_detail_content: true
    content_xpath:
    - //div[@class='cb-post__body']
    - //div[@class='cb-post__body']
    text_xpath:
    - .//div[@class='cb-content-block cb-content-block-text cb-post-block cb-post-block-text
      gtm-cb-post-block-text']/div[@class='cb-content-block-text__text cb-content-block__content
      cb-post-block__content']/p
    image_box_xpath:
    - //cb-post-block-images/open-gallery-button
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://carbuzz.com
    minimum_topic_length: 4
    tags: []
    only_quality_post: false
    browser_timeout: 60
    prevent_auto_redirect: false
    remove_me: false