- Oto_com_vn:
    id_type: href
    browser_profile: ''
    web_url: https://oto.com.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //h2[@class="description"]
    - //h2[@class="description"]
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 26/11/2020 03:36
    contain: ''
    crawl_url: https://oto.com.vn/tin-tuc
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //span[@class="date"]
    - //span[@class="date"]
    topic_type: href
    maximum_url: 50
    get_detail_content: true
    content_xpath:
    - //div[@id="contentNewsMain"]/div[1]
    - //div[@id="contentNewsMain"]/div[1]
    text_xpath:
    - ./p
    image_box_xpath:
    - .//p[(contains(@style,"center"))]
    image_title_xpath:
    - //img/@alt
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://oto.com.vn
    minimum_topic_length: 4
    tags: []
    only_quality_post: true
    browser_timeout: 60
    prevent_auto_redirect: false
    remove_me: false